version: '3'

services:
  tesseract-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    # command: bash
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "production_status"
    command: ["tail", "-f", "/dev/null"]